### ISSUE TITLE
"New subject" is displayed for every reply on web interface

### ISSUE THREAD

**Issue by Lastique** [cppalliance/boost-mailman#5]
https://lists.preview.boost.org/archives/list/boost@lists.preview.boost.org/thread/4JWMKKOVJXHLMBUIG6UQFTG74YAI2X5P/

In this and other threads, every reply has a "New subject: ..." writing next to the author's name.

![Screenshot_20240605_005008](https://github.com/cppalliance/boost-mailman/assets/1589747/4839b972-6118-49d5-b8be-07efc98f2429)

I'm not sure what this writing is supposed to convey, as the subject is the same as the original message, plus the "[boost]" tag. It is also displayed seemingly out of place as it is right next to the author's name and visually associates with the author. I don't see it in a newer thread, like this one:

https://lists.preview.boost.org/archives/list/boost@lists.preview.boost.org/thread/NJKVW7KRLSALK2VQ7XW7LPBIB22ESM7E/

If it is fixed already then feel free to close this. Otherwise, I think it should be removed. Or at the very least, it should be displayed further away from the author's name (perhaps, aligned to right, or below the author's name or something).

**Comment by sdarwin** [comment]
- I opened a Hyperkitty pull request to re-position the "New subject" message.
- Regardless of that, it's solved, by setting the list to use [boost] (lowercase as before) instead of [Boost].   Check the link now https://lists.preview.boost.org/archives/list/boost@lists.preview.boost.org/thread/4JWMKKOVJXHLMBUIG6UQFTG74YAI2X5P/
